project_id = "wzdqarazpikspxnrbemt"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-to-external]
verify_jwt = false

[functions.sync-stripe-products]
verify_jwt = false

[functions.retry-payment-sync]
verify_jwt = false

[functions.sync-plans-to-external]
verify_jwt = false

[functions.ga-analytics]
verify_jwt = true
